repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.4
    hooks:
      - id: commitizen
        language_version: python3.13 # match your installed Python
        stages: ["commit-msg"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: poetry run mypy
        language: system # use system Poetry venv
        types: [python]
        require_serial: true
